### ISSUE TITLE
[Bug]: can't use tabs component in playground

### ISSUE THREAD

**Issue by jiaqidegege** [zhixiaoqiang/sfc-playground-vant#61]
### Details

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/31435549/229435423-8afc83a1-7f72-4726-8bca-7a0efef1f180.png">

### Reproduce link

https://sfc-playground-vant.vercel.app/#eNp9VMtu2zAQ/BVCFymoJRVtenHjNEXQQ28FWvSkiyytbSYUSZCU48Dwv3eWihXFdXwRRM7scLgP7pPv1hbbnpJ5cuMbJ20QnkJvhar1epEGn95WWnbWuCD2wtFKHMTKmU6kCEon0J966Wf8fSXUOqRfKz0hSf1ATfgLYGQVJfPyAcmt6tdSFw8e0ogb6dlVpRujfRB1I7ckFmwl+4jdm3KwDZtYBOqsqgNhJcQNlPMAX2Kbd6YlNa+bgOhFlQw/VRJ5r0wQV8YBl7qlHeyK6yoR8yCD4qgUlFR8wD7QMVgIOAuEO5mVYJE9X5TjD4cXeb4j67PJMK784LmcmE5myZCsvKst0mA0CrNnFXiKgK+SuYg7vIci8LpKNiFYPy/LXtvHddGYrrwDVrpeB9lR3pru7nPxqbj+UrbSh+l+Qb7Ll848eXI4sUpmozgS/546Y6WSy/gDibeRdxHu/QVzL4RvKEyvwDuJtcZacix6SeDIek8lmL7Z5NT1SK9xl7VOuayE+h1QkrMdisKMfb2mcN87hx74iR6tdUMnYzLOQOz9yXyMQHrORYykXSSseo2mNXoyRNnV0AnDZMjj0YszfniAxEgpamvvuWl3gX8LFCJjQZBw5f+PBId0+zs8KwgNZzq8Ek4LTU/iF64joZA58kZtaQaQLV6Jxe2xVQeLSupH2GtN03cwVzSO0Pc/FPEqSxlOo1ERqYUjBXrq+WC/IeJ8jeCGXyOgF5ozjmHReH5Oxjijlanb+IREu28gcs64iPENBmi0uzTtM+cLubjfSNVmHBT9Ho6Zq59qiUdqmi9M9eEf6nngoA==

**Comment by zhixiaoqiang** [comment]
thanks for you Issue

**Comment by zhixiaoqiang** [comment]
temporary solution:

replace Import Map `vant` cdn to: https://unpkg.com/vue@^3.0.0?module

![image](https://user-images.githubusercontent.com/25545093/229444645-f2a5dceb-46a4-4b93-b0fc-3ad270db7189.png)

looks like `@vant/use` import `vue` version inconsistent

![image](https://user-images.githubusercontent.com/25545093/229446013-2a93b6ef-2716-4bd3-9666-e9f08df54a39.png)

https://unpkg.com/vue@^3.0.0?module

**Comment by jiaqidegege** [comment]
It worked. Thanks for your great work. it makes a great convience for me to use vant.

**Comment by zhixiaoqiang** [comment]
fixing
