### ISSUE TITLE
[Bug]: Failed to resolve module specifier "@vue/shared".

### ISSUE THREAD

**Issue by wtto00** [zhixiaoqiang/sfc-playground-vant#79]
### Details

![image](https://github.com/zhixiaoqiang/sfc-playground-vant/assets/30424139/5b513210-6ed7-404b-b54c-93987929005d)

默认的示例项目报错，如上图

### Reproduce link

https://sfc-playground-vant.vercel.app/

**Comment by zhixiaoqiang** [comment]
thanks for you Issue

**Comment by wtto00** [comment]
"@vue/shared": "https://unpkg.com/@vue/shared?module"

Import Map 加上这一句就好了

**Comment by zhixiaoqiang** [comment]
fixed
历史的也兼容了
